// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/service.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	pb/service.proto

It has these top-level messages:
	MsgRequest
	MsgResponse
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MsgRequest struct {
	Value string `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
}

func (m *MsgRequest) Reset()                    { *m = MsgRequest{} }
func (m *MsgRequest) String() string            { return proto.CompactTextString(m) }
func (*MsgRequest) ProtoMessage()               {}
func (*MsgRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *MsgRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type MsgResponse struct {
	Value string `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
}

func (m *MsgResponse) Reset()                    { *m = MsgResponse{} }
func (m *MsgResponse) String() string            { return proto.CompactTextString(m) }
func (*MsgResponse) ProtoMessage()               {}
func (*MsgResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *MsgResponse) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*MsgRequest)(nil), "example.MsgRequest")
	proto.RegisterType((*MsgResponse)(nil), "example.MsgResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ReplyService service

type ReplyServiceClient interface {
	Reply(ctx context.Context, in *MsgRequest, opts ...grpc.CallOption) (*MsgResponse, error)
}

type replyServiceClient struct {
	cc *grpc.ClientConn
}

func NewReplyServiceClient(cc *grpc.ClientConn) ReplyServiceClient {
	return &replyServiceClient{cc}
}

func (c *replyServiceClient) Reply(ctx context.Context, in *MsgRequest, opts ...grpc.CallOption) (*MsgResponse, error) {
	out := new(MsgResponse)
	err := grpc.Invoke(ctx, "/example.ReplyService/Reply", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ReplyService service

type ReplyServiceServer interface {
	Reply(context.Context, *MsgRequest) (*MsgResponse, error)
}

func RegisterReplyServiceServer(s *grpc.Server, srv ReplyServiceServer) {
	s.RegisterService(&_ReplyService_serviceDesc, srv)
}

func _ReplyService_Reply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplyServiceServer).Reply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/example.ReplyService/Reply",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplyServiceServer).Reply(ctx, req.(*MsgRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ReplyService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "example.ReplyService",
	HandlerType: (*ReplyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Reply",
			Handler:    _ReplyService_Reply_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/service.proto",
}

func init() { proto.RegisterFile("pb/service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 189 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x28, 0x48, 0xd2, 0x2f,
	0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4f, 0xad,
	0x48, 0xcc, 0x2d, 0xc8, 0x49, 0x95, 0x92, 0x49, 0xcf, 0xcf, 0x4f, 0xcf, 0x49, 0xd5, 0x4f, 0x2c,
	0xc8, 0xd4, 0x4f, 0xcc, 0xcb, 0xcb, 0x2f, 0x49, 0x2c, 0xc9, 0xcc, 0xcf, 0x2b, 0x86, 0x28, 0x53,
	0x52, 0xe2, 0xe2, 0xf2, 0x2d, 0x4e, 0x0f, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x12, 0xe1,
	0x62, 0x2d, 0x4b, 0xcc, 0x29, 0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0x70, 0x94,
	0x94, 0xb9, 0xb8, 0xc1, 0x6a, 0x8a, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0xb1, 0x2b, 0x32, 0x8a, 0xe3,
	0xe2, 0x09, 0x4a, 0x2d, 0xc8, 0xa9, 0x0c, 0x86, 0xb8, 0x42, 0xc8, 0x8f, 0x8b, 0x15, 0xcc, 0x17,
	0x12, 0xd6, 0x83, 0xba, 0x44, 0x0f, 0x61, 0x91, 0x94, 0x08, 0xaa, 0x20, 0xc4, 0x64, 0x25, 0xa9,
	0xa6, 0xcb, 0x4f, 0x26, 0x33, 0x89, 0x28, 0xf1, 0xeb, 0x97, 0x19, 0xea, 0x17, 0x81, 0x74, 0x43,
	0x48, 0x2b, 0x46, 0x2d, 0x27, 0x96, 0x28, 0xa6, 0x82, 0xa4, 0x24, 0x36, 0xb0, 0xab, 0x8d, 0x01,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x84, 0x51, 0x63, 0x05, 0xf0, 0x00, 0x00, 0x00,
}
